In [21]:
import pandas as pd
df = pd.DataFrame(

    {

        "Name": [

            "Hasan, M",

            "Ali, M",

            "Alex, Samuel",

        ],

        "Age": [17, 26, 36],

        "Sex": ["male", "male", "male"],
        
        "PoB":["NY","LON","BER"],
       

    }

)
df.head()

           Name  Age   Sex  PoB
0      Hasan, M   17  male   NY
1        Ali, M   26  male  LON
2  Alex, Samuel   36  male  BER

In [22]:
df["Age"]

0    17
1    26
2    36
Name: Age, dtype: int64

In [23]:
ages = pd.Series([22,35,58], name="Age")
ages

0    22
1    35
2    58
Name: Age, dtype: int64

In [24]:
df["Age"].max()

np.int64(36)

In [25]:
ages.max()

np.int64(58)

In [26]:
df.describe()

             Age
count   3.000000
mean   26.333333
std     9.504385
min    17.000000
25%    21.500000
50%    26.000000
75%    31.000000
max    36.000000

In [27]:
data = pd.read_csv("fdata.csv")

In [28]:
data.head(4)

    Name         city  age  py-score
0  Marco  Mexico City   41      88.0
1    Ann      Toronto   28      79.0
2   Jana       Prague   33      81.0
3     Yi     Shanghai   34      80.0

In [29]:
data

    Name         city  age  py-score
0  Marco  Mexico City   41      88.0
1    Ann      Toronto   28      79.0
2   Jana       Prague   33      81.0
3     Yi     Shanghai   34      80.0
4  Robin   Manchester   38      68.0
5   Amal        Cairo   31      61.0
6   Nori        Osaka   37      84.0

In [30]:
data.tail(3)

    Name        city  age  py-score
4  Robin  Manchester   38      68.0
5   Amal       Cairo   31      61.0
6   Nori       Osaka   37      84.0

In [31]:
data["Name"]

0    Marco
1      Ann
2     Jana
3       Yi
4    Robin
5     Amal
6     Nori
Name: Name, dtype: object

In [32]:
data.dtypes

Name         object
city         object
age           int64
py-score    float64
dtype: object

In [33]:
data.to_excel("data.xlsx", sheet_name="passengers", index=False)

In [34]:
data1=pd.read_excel("data.xlsx", sheet_name="passengers")

In [35]:
data1

    Name         city  age  py-score
0  Marco  Mexico City   41        88
1    Ann      Toronto   28        79
2   Jana       Prague   33        81
3     Yi     Shanghai   34        80
4  Robin   Manchester   38        68
5   Amal        Cairo   31        61
6   Nori        Osaka   37        84

In [36]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      7 non-null      object
 1   city      7 non-null      object
 2   age       7 non-null      int64
 3   py-score  7 non-null      int64
dtypes: int64(2), object(2)
memory usage: 356.0+ bytes

In [37]:
data1.to_csv("data2.csv", index=False)

In [38]:
titanic=pd.read_csv("titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [40]:
ages=titanic["Age"]
ages.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [41]:
titanic["Age"].shape

(891,)

In [42]:
age_sex=titanic[["Age","Sex"]]
age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [43]:
type(titanic[["Age", "Sex"]])

pandas.core.frame.DataFrame

In [44]:
titanic[["Age", "Sex"]].shape

(891, 2)

In [45]:
above_35=titanic[titanic["Age"]>35]

In [46]:
above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [47]:
titanic["Age"]>35

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [48]:
above_35.shape

(217, 12)

In [49]:
# the Titanic passengers from cabin class 2 and 3.
class_23 = titanic[titanic["Pclass"].isin([2, 3])]
class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [50]:
age_no_na = titanic[titanic["Age"].notna()]
age_no_na.head()
#The notna() conditional function returns a True for each row the values are not an Null value.
#This is for data which is known

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [51]:
age_no_na.shape

(714, 12)

In [52]:
#specific rows and columns from a data frame.
#names of passengers older than 35 years.
adult_names = titanic.loc[titanic["Age"]>35, "Name"]
adult_names.head()
#loc attribute access a group of rows and columns by label(s) or a boolean array in the given DataFrame

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
6                               McCarthy, Mr. Timothy J
11                             Bonnell, Miss. Elizabeth
13                          Andersson, Mr. Anders Johan
15                     Hewlett, Mrs. (Mary D Kingcome)
Name: Name, dtype: object

In [53]:
#rows 10 till 25 and columns 3 to 5.
titanic.iloc[9:25, 2:6]
#iloc” in pandas is used to select rows and columns by number, in the order that they appear in the data frame.

    Pclass                                               Name     Sex   Age
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
10       3                    Sandstrom, Miss. Marguerite Rut  female   4.0
11       1                           Bonnell, Miss. Elizabeth  female  58.0
12       3                     Saundercock, Mr. William Henry    male  20.0
13       3                        Andersson, Mr. Anders Johan    male  39.0
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0
16       3                               Rice, Master. Eugene    male   2.0
17       2                       Williams, Mr. Charles Eugene    male   NaN
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0
19       3                            Masselmani, Mrs. Fatima  female   NaN
20       2                               Fynney, Mr. Joseph J    male  35.0
21       2                              Beesley, Mr. Lawrence    male  34.0
22       3                        McGowan, Miss. Anna "Annie"  female  15.0
23       1                       Sloper, Mr. William Thompson    male  28.0
24       3                      Palsson, Miss. Torborg Danira  female   8.0

In [54]:
#When selecting specific rows and/or columns with loc or iloc, new values can be assigned to the selected data.
titanic.iloc[0:3,3]="anonymous"
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,anonymous,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,anonymous,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,anonymous,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Select specific rows and/or columns using loc when using the row and column names

Select specific rows and/or columns using iloc when using the positions in the table

You can assign new values to a selection based on loc/iloc.